# After changing this file, run it through http://lint.travis-ci.org/
# Generates 4 builds, the ones for python3 will install external wheels
language: python
matrix:
  include:
    - python: 2.6
      env:
        - SCIPYSPEC===0.12.0
    - python: 2.7
      env:
        - SCIPYSPEC===0.12.0
    - python: 3.2
      env:
        - NUMPYSPEC===1.8.0
        - SCIPYSPEC===0.13.1
    - python: 3.3
      env:
        - NUMPYSPEC===1.8.0
        - SCIPYSPEC===0.13.1
before_install:
  - sudo add-apt-repository -y ppa:biometrics/bob
  - sudo add-apt-repository -y ppa:biometrics/bob.preview
  - sudo apt-get update -qq
  - sudo apt-get install -qq --force-yes bob-dev
  - sudo apt-get install -qq python-imaging
  - sudo apt-get install -qq libsvm-dev
  - sudo apt-get install -qq python-opencv libcv-dev libcvaux-dev libopencv-dev
  - sudo apt-get install -qq libatlas-dev libatlas-base-dev liblapack-dev gfortran
  - pip install --upgrade pip setuptools
  - if [ -n "${NUMPYSPEC}" ]; then pip install --find-links http://wheels.astropy.org/ --find-links http://wheels2.astropy.org/ --use-wheel numpy$NUMPYSPEC; fi
  - pip install --find-links http://wheels.astropy.org/ --find-links http://wheels2.astropy.org/ --use-wheel matplotlib scipy$SCIPYSPEC sphinx nose
  - pip install cpp-coveralls
install:
  - "python bootstrap.py"
  - "./bin/buildout"
  - "CFLAGS=-coverage ./bin/buildout"
script:
  - "./bin/coverage run --source=facereclib ./bin/nosetests -sv"
  - "./bin/sphinx-build -b doctest docs sphinx"
  - "./bin/sphinx-build -b html docs sphinx"
after_success:
  - "coveralls --build-root=`pwd` --exclude=src"
